server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - http://localhost:5173
                  - http://localhost
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowed-headers:
                  - Authorization
                  - Content-Type
                  - Accept
                exposed-headers:
                  - Authorization
                allow-credentials: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              predicates:
                - name: Path
                  args:
                    pattern: "'/'+serviceId+'/**'"
              filters:
                - name: RewritePath
                  args:
                    regexp: "'/' + serviceId + '/?(?<remaining>.*)'"
                    replacement: "'/${remaining}'"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka